barra/barra/urls.py
from django.contrib import admin
from django.urls import path

from inventario import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
	path('password/', views.password, name='password'),
	path('asignacion/', views.asignacion, name='asignacion'),
	path('persona/', views.persona, name='persona'),
]

barra/inventario/models.py
from django.db import models

# Create your models here.


class Registrado(models.Model):
	nombre = models.CharField(max_length=100, blank=False, null=True)
	email = models.EmailField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return self.email

	def __str__(self):
		return self.email
		

class Equipos(models.Model):
	descripcion = models.CharField(max_length=100, blank=False, null=False)
	modelo = models.CharField(max_length=100, blank=False, null=False)
	serial = models.CharField(max_length=100, blank=False, null=False)
	#id_persona = models.CharField(max_length=20, blank=True, null=True)
	id_persona = models.ForeignKey(
		'Personas', on_delete=models.CASCADE, blank=True, null=True)
	#imagen = models.URLField()



class Personas(models.Model):
	#nombre = models.ManyToManyField(Equipos1)
	nombre = models.CharField(max_length=50, blank=False, null=False)
	departamento = models.CharField(max_length=50, blank=False, null=False)
	
	def prueba(self):
		return self.nombre

	def __str__(self):
		return self.nombre


"""
class 
class Change_Pass(models.Model):
	descripcion = models.CharField(max_length=100, blank=False, null=False)
	modelo = models.CharField(max_length=100, blank=False, null=False)
	serial = models.CharField(max_length=100, blank=False, null=False)
	#imagen = models.URLField()
"""

barra/inventario/forms.py
from django import forms
from .models import Registrado, Equipos, Personas

#from .models import Equipos
#from .models import Personas

#-- --------------------- Formulario Admin ------------------------------------- -->
class RegModelForm(forms.ModelForm):
	class Meta:
		model = Registrado
		fields = ["nombre", "email"]
		
	def clean_email(self):
		email = self.cleaned_data.get("email")
		email_base, proveeder = email.split("@")
		dominio, extension = proveeder.split(".")
		if not extension == "edu":
			raise forms.ValidationError("Solo correos .EDU")
		return email
class RegForm(forms.Form):
	nombre = forms.CharField(max_length=100)
	email = forms.EmailField()


#-- --------------------- Formulario Generar codigo ---------------------------- -->
	#-- ----- Recibir Datos ----- -->
class FormCodigo(forms.ModelForm):
	class Meta:
		model = Equipos
		fields = ["descripcion", "modelo", "serial"]
class RegFormCodigo(forms.Form):
	descripcion = forms.CharField(max_length=30)
	modelo = forms.CharField(max_length=30)
	serial = forms.CharField(max_length=30)

#-- ----- Mostrar Imagen ----- -->



#-- --------------------- Formulario Cambio de Clave --------------------------- -->
#-- ----- Recibir Datos ----- -->
class FormPassword(forms.ModelForm):
	"""class Meta:
		model = Codigo_de_Barras
		fields = ["pass_last", "pass_new"]"""
class RegFormPassword(forms.Form):
	pass_last = forms.CharField(max_length=30)
	pass_new = forms.CharField(max_length=30)



#-- --------------------- Formulario Asignacion de Equipos --------------------- -->
#-- ----- Recibir Datos ----- -->
class FormAsignacion(forms.ModelForm):
	"""class Meta:
		model = Codigo_de_Barras
		fields = ["descripcion", "modelo", "serial"]"""
class RegFormAsignacion(forms.Form):
	descripcion = forms.CharField(max_length=30)
	modelo = forms.CharField(max_length=30)
	serial = forms.CharField(max_length=30)



#-- ---------------------------- Formulario Personas ---------------------------- -->
#-- ----- Recibir Datos ----- -->
class FormPersonas(forms.ModelForm):
	class Meta:
		model = Personas
		fields = ["nombre", "departamento"]
class RegFormPersonas(forms.Form):
	nombre = forms.CharField(max_length=50)
	departamento = forms.CharField(max_length=50)

barra/inventario/views.py
from django.shortcuts import render

# Create your views here.

#from .forms import RegForm
from .forms import FormCodigo, FormPassword
from .forms import FormAsignacion, FormPersonas

from django.contrib.auth.models import User
from .models import Registrado, Equipos, Personas

import code128
import os


# Create your views here.

#-- -------------------------- Vista Admin -------------------------- -->
"""def inicio1(request):
	form = RegForm(request.POST or None)
	if form.is_valid():
		form_data = form.cleaned_data
		abc = form_data.get("email")
		asd = form_data.get("nombre")
		obj = Registrado.objects.create(email=abc, nombre=asd)
	context = {
		"el_form": form,
	}
	return render(request, "index.html", context)
"""

#-- --------------------- Vista Generar Codigo --------------------- -->
def index(request):
	form = FormCodigo(request.POST)
	if form.is_valid():
		form_data = form.cleaned_data
		v_descripcion = form_data.get('descripcion')
		v_modelo = form_data.get("modelo")
		v_serial = form_data.get("serial")
		obj = Equipos.objects.create(descripcion=v_descripcion, 
		                            modelo=v_modelo, 
		                            serial=v_serial
		                            )
		ruta = r'static/imagen_codigo/'
		if not os.path.exists(ruta): os.makedirs(ruta)
		code128.image(v_descripcion + ' ' + v_modelo + ' ' +
						v_serial).save(ruta + v_serial + ".png")
	context = {
		"el_form": form,
	}
	return render(request, "index.html", context)


#-- --------------------- Vista Cambio de Clave --------------------- -->
def password(request):
	"""
	form = FormPassword(request.POST)
	if form.is_valid():
		form_data = form.cleaned_data
		v_pass_last = form_data.get("pass_last")
		v_rep_new = form_data.get("pass_new")
		

		#obj = User.objects.get(username='usuario')
		obj = User.objects.get(username = v_pass_last)
		obj.set_password(v_rep_new)
		obj.save()

	context = {
		"el_form": form,
	}
	return render(request, "password.html")
#-------------------------------------------------------------------------------

	form = FormPassword(request.POST)
	if form.is_valid():
		form_data = form.cleaned_data
		v_pass_last = form_data.get("pass_last")
		v_pass_new = form_data.get("pass_new")

		user = User.objects.get(username=v_pass_last)
		user.set_password(v_pass_new)
		user.save()

		if user.save():
			print('Excelente')
		else: 
			print('No se cambio')

	context = {
		"el_form": form,
	}
	"""
	return render(request, "password.html")




#-- --------------------- Vista Asignacion de Equipos --------------------- -->
def asignacion(request):
	"""
	form = FormAsignacion(request.POST)
	if form.is_valid():
		form_data = form.cleaned_data
		v_pass_last = form_data.get("pass_last")
		v_pass_new = form_data.get("pass_new")
		v_rep_pass = form_data.get("rep_pass")
		obj = Change_Pass.objects.create(pass_last=v_pass_last, 
		                                 pass_new=v_pass_new, 
		                                 rep_pass=v_rep_pass
		                                      )
	context = {
		"el_form": form,
	}
	return render(request, "asignacion.html", context)
	"""
	equipos = Equipos.objects.all()
	print(equipos)
	return render(request, "asignacion.html", 
	              {'result': equipos})


#-- --------------------- Vista Personas --------------------- -->
def persona(request):		
	form = FormPersonas(request.POST)
	if form.is_valid():
		form_data = form.cleaned_data
		v_nom_apel = form_data.get("nombre")
		v_depart = form_data.get("departamento")
		obj = Personas.objects.create(nombre=v_nom_apel, 
		                              departamento=v_depart, 
		                              )
	result = Personas.objects.all()
	context = {
		"el_form": form,
	              'result': result
	}
	return render(request, "persona.html", context)
	
	#return render(request, "persona.html")
	

barra/templates/asignacion.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<title>Equipos Asignados</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	
<link rel="stylesheet" href="{% static '/materialize/css/materialize.min.css' %}" media="screen,projection">
<link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static '/style.css' %}">

</head>
<body>

	<div class="col m12 s12 x12 navbar-fixed">
    <nav>
      <span class="left brand-logo text-darken-2">
      <i onclick="Materialize.showStaggeredList('#slide-out')" id="btnMenu" data-activates="slide-out" class="deslizar icono-menu fa fa-bars fa-2x "></i>
      </span> 
      <h4 class="center-align "> <span class="hide-on-small-only">Equipos</span> Asignados</h4>
     <!-- <h4 class="center-align "> Asignados</h4>-->
    </nav>
  </div>
    

  <ul id="slide-out" class="side-nav ">
      <li>  
        <i class="iconos-pequeno prefix fa fa-user-o fa-2x"></i>        
      </li>
      <!-- <li>
          <div class="divider"></div>
        </li> -->  
    <li class=" ">
      <a href="/" class="btn"><i class="iconos-pequeno fa fa-home fa-1x" ></i> Inicio</a>
    </li>
    <li>
      <a href="/persona" class="btn"><i class="iconos-pequeno fa fa-user fa-1x" ></i> Agregar Personas </a> 
    </li>
    <li class=" ">
      <a href="/asignacion" class="active-btn btn"><i class="iconos-pequeno fa fa-desktop fa-1x" ></i> Equipos Asignados</a>
    </li>
    <li class=" ">
      <a href="/password" class="btn"><i class="iconos-pequeno fa fa-key fa-1x" ></i> Cambiar Contraseña</a>
    </li>
    <li class=" ">
      <a href="" class="btn"><i class="iconos-pequeno fa fa-cog fa-1x" ></i> Opciones</a>
    </li>
    <li class=" " >
      <a href="" class="btn"><i class="iconos-pequeno fa fa-power-off fa-1x" ></i> Cerrar Sección</a>
    </li>
  </ul>
  
  <div class="container ">
    <div class=" row">
      <div class=" col m12 s12 x12">    
      <form action="" method=" ">
              <table id="id_table" class="bordered highlight centered" >
                    <thead>
                      <tr>
                          <th>Asignado</th>
                          <th>Descripción</th>
                          <th>Modelo</th>
                          <th>Serial</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for  r in result %}
                        <tr>
                          <td>{{ r.id_persona.nombre}}</td>
                          <td>{{ r.descripcion }}</td>
                          <td>{{ r.modelo }}</td>
                          <td>{{ r.serial }}</td>              
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>             
			</form>
		</div>
		</div>
	</div>



  <script src="{% static '/jquery/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static '/materialize/js/materialize.min.js' %}"></script>
  <script src="{% static '/materialize/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static '/materialize/js/jquery.dataTables.js' %}"></script>
  <script src="{% static '/materialize/js/dataTables.bootstrap.min.js' %}"></script>
  <script src="{% static '/style.js' %}"></script>
    
</body>
</html>

barra/templates/asignacion1.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<title>Equipos Asignados</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	
<link rel="stylesheet" href="{% static '/materialize/css/materialize.min.css' %}" media="screen,projection">
<link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static '/style.css' %}">

</head>
<body>

	<div class="col m12 s12 x12 navbar-fixed">
    <nav>
      <span class="left brand-logo text-darken-2">
      <i onclick="Materialize.showStaggeredList('#slide-out')" id="btnMenu" data-activates="slide-out" class="deslizar icono-menu fa fa-bars fa-2x "></i>
      </span> 
      <h4 class="center-align "> <span class="hide-on-small-only">Equipos</span> Asignados</h4>
     <!-- <h4 class="center-align "> Asignados</h4>-->
    </nav>
  </div>
    

  <ul id="slide-out" class="side-nav ">
      <li>  
        <i class="iconos-pequeno prefix fa fa-user-o fa-2x"></i>        
      </li>
      <!-- <li>
          <div class="divider"></div>
        </li> -->  
    <li class=" ">
      <a href="/" class="btn"><i class="iconos-pequeno fa fa-home fa-1x" ></i> Inicio</a>
    </li>
    <li>
      <a href="/persona" class="btn"><i class="iconos-pequeno fa fa-user fa-1x" ></i> Agregar Personas </a> 
    </li>
    <li class=" ">
      <a href="/asignacion" class="active-btn btn"><i class="iconos-pequeno fa fa-desktop fa-1x" ></i> Equipos Asignados</a>
    </li>
    <li class=" ">
      <a href="/password" class="btn"><i class="iconos-pequeno fa fa-key fa-1x" ></i> Cambiar Contraseña</a>
    </li>
    <li class=" ">
      <a href="" class="btn"><i class="iconos-pequeno fa fa-cog fa-1x" ></i> Opciones</a>
    </li>
    <li class=" " >
      <a href="" class="btn"><i class="iconos-pequeno fa fa-power-off fa-1x" ></i> Cerrar Sección</a>
    </li>
  </ul>
  
  <div class="container ">
    <div class=" row">
      <div class=" col m12 s12 x12">    
      <form action="" method=" ">
              <table id="id_table" class="bordered highlight centered" >
                    <thead>
                      <tr>
                          <th>Asignado</th>
                          <th>Descripción</th>
                          <th>Modelo</th>
                          <th>Serial</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for  r in result %}
                        <tr>
                          <td>{{ r.nombre }}</td>
                          <td>{{ r.equipos.Equipos1 }}</td>
                          <td>{{ r.equipos }}</td>
                          <td>{{ r.departamento }}</td>              
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>             
			</form>
		</div>
		</div>
	</div>



  <script src="{% static '/jquery/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static '/materialize/js/materialize.min.js' %}"></script>
  <script src="{% static '/materialize/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static '/materialize/js/jquery.dataTables.js' %}"></script>
  <script src="{% static '/materialize/js/dataTables.bootstrap.min.js' %}"></script>
  <script src="{% static '/style.js' %}"></script>
    
</body>
</html>

barra/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<title>Código de Barra</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	
	<link rel="stylesheet" href="{% static '/materialize/css/materialize.min.css' %}" media="screen,projection">
    <link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static '/style.css' %}">


</head>
<body>

	  <div class="col m12 s12 x12 navbar-fixed">
			<nav>
			<span class="left brand-logo text-darken-2">
				<i onclick="Materialize.showStaggeredList('#slide-out')" id="btnMenu" data-activates="slide-out" class=" deslizar icono-menu fa fa-bars fa-2x "></i>
			</span>	
			<h4 class="center-align"><span class="hide-on-small-only">Agregar</span> Equipos</h4>		
		</nav>
	</div>

	<ul id="slide-out" class="side-nav ">
	    <li>  
	    	<i class="iconos-pequeno prefix fa fa-user-o fa-2x"></i>        
	    </li>
	    <!-- <li>
	      	<div class="divider"></div>
	      </li> -->      
		 <li class=" ">
	      <a href="/" class="active-btn btn"><i class="iconos-pequeno fa fa-home fa-1x" ></i> Inicio</a>
	    </li>
		<li>
			<a href="/persona" class="btn"><i class="iconos-pequeno fa fa-user fa-1x" ></i> Agregar Personas </a> 
		</li>
		<li class=" ">
			<a href="/asignacion" class="btn"><i class="iconos-pequeno fa fa-desktop fa-1x" ></i> Equipos Asignados</a>
		</li>
		<li class=" ">
			<a href="/password" class="btn"><i class="iconos-pequeno fa fa-key fa-1x" ></i> Cambiar Contraseña</a>
		</li>
		<li class=" ">
			<a href="" class="btn"><i class="iconos-pequeno fa fa-cog fa-1x" ></i> Opciones</a>
		</li>
		<li class=" " >
			<a href="" class="btn"><i class="iconos-pequeno fa fa-power-off fa-1x" ></i> Cerrar Sección</a>
		</li>
	</ul>

	<div class="container ">
		<div class=" row">
			<div class=" box1 col m10 offset-m1 s12 x12">    
			<form action="" method="POST">{% csrf_token %}

			    <!--   Codigo   -->
			    <div class="input-field">    
			        <i class="prefix fa fa-edit fa-3x"></i>
			        <input id="id_descripcion" name="descripcion" type="text" required> 
			        <label for="id_descripcion" class="active">Descripcion</label>
			    </div>

			    <!--  Descripción  -->
			    <div class="input-field">    
			        <i class="prefix fa fa-edit fa-3x"></i>
			        <input id="id_modelo" name="modelo" type="text" required> 
			        <label for="id_modelo" class="active">Modelo</label>
			    </div>

			    <!--  Usuario  -->    
			    <div class="input-field">    
			        <i class="prefix fa fa-hashtag fa-3x"></i>
			        <input id="id_serial" name="serial" type="text" required> 
			        <label for="id_serial" class="active">Serial</label>
			    </div>

			    <!--   Boton   --> 
			    <div class=" center group navform wat-cf">
			        <button class="boton-generar-codigo hoverable waves-effect" type="submit">Generar Codigo</button>
			    </div>                        
			</form>
		</div>
		</div>
	</div>

	<script src="{% static '/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static '/materialize/js/materialize.min.js' %}"></script>
	<script src="{% static '/style.js' %}"></script>
</body>
</html>

barra/templates/password.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<title>Cambiar Clave</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	
	<link rel="stylesheet" href="{% static '/materialize/css/materialize.min.css' %}" media="screen,projection">
    <link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static '/style.css' %}">


</head>
<body>

	  <div class="col m12 s12 x12 navbar-fixed">
		<nav>
			<span class="left brand-logo text-darken-2">
			<i onclick="Materialize.showStaggeredList('#slide-out')" id="btnMenu" data-activates="slide-out" class="deslizar icono-menu fa fa-bars fa-2x "></i>
			</span>	
			<h4 class="center-align "> <span class="hide-on-small-only">Cambiar</span> Contraseña</h4>
		</nav>
	</div>
		
  <ul id="slide-out" class="side-nav ">
      <li>  
        <i class="iconos-pequeno prefix fa fa-user-o fa-2x"></i>        
      </li>
      <!-- <li>
          <div class="divider"></div>
        </li> -->  
    <li class=" ">
      <a href="/" class="btn"><i class="iconos-pequeno fa fa-home fa-1x" ></i> Inicio</a>
    </li>
    <li>
      <a href="/persona" class="btn"><i class="iconos-pequeno fa fa-user fa-1x" ></i> Agregar Personas </a> 
    </li>
    <li class=" ">
      <a href="/asignacion" class="btn"><i class="iconos-pequeno fa fa-desktop fa-1x" ></i> Equipos Asignados</a>
    </li>
    <li class=" ">
      <a href="/password" class="active-btn btn"><i class="iconos-pequeno fa fa-key fa-1x" ></i> Cambiar Contraseña</a>
    </li>
    <li class=" ">
      <a href="" class="btn"><i class="iconos-pequeno fa fa-cog fa-1x" ></i> Opciones</a>
    </li>
    <li class=" " >
      <a href="" class="btn"><i class="iconos-pequeno fa fa-power-off fa-1x" ></i> Cerrar Sección</a>
    </li>
  </ul>

<div class="container ">
	<div class=" row">
		<div class=" box1 col m6 offset-m3 s12 x12">    
			<form action="" method="POST">{% csrf_token %}

			    <!--   Codigo   -->
			    <div class="input-field">    
			        <i class="prefix fa fa-key fa-3x"></i>
			        <input id="pass_ant" name="pass_last" type="text" required> 
			        <label for="pass_ant" class="active">Contraseña Anterior</label>
			    </div>

			    <!--  Descripción  -->
			    <div class="input-field">    
			        <i class="prefix fa fa-key fa-3x"></i>
			        <input id="pass_nue" name="pass_new" type="password" required> 
			        <label for="pass_nue" class="active">Contraseña Nueva</label>
			    </div>

			    <!--  Usuario  -->    
			    <div class="input-field">    
			        <i class="prefix fa fa-key fa-3x"></i>
			        <input id="rep_pass" name="rep_pass" type="password" required> 
			        <label for="rep_pass" class="active">Confirmar Nueva Contraseña</label>
			    </div>

			    <!--   Boton   --> 
			    <div class=" center group navform wat-cf">
			        <button class="boton-guardar-contrasena hoverable waves-effect" type="submit">Guardar Cambios</button>
			    </div>                        
			</form>
		</div>
	</div>
</div>

	<script src="{% static '/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static '/materialize/js/materialize.min.js' %}"></script>
	<script src="{% static '/style.js' %}"></script>
</body>
</html>

barra/templates/persona.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
	<title>Agregar Personas</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
	
<link rel="stylesheet" href="{% static '/materialize/css/materialize.min.css' %}" media="screen,projection">
<link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static '/style.css' %}">

</head>
<body>

    <div class="col m12 s12 x12 navbar-fixed">
		<nav>
		    <span class="left brand-logo text-darken-2">
		      <i onclick="Materialize.showStaggeredList('#slide-out')" id="btnMenu" data-activates="slide-out" class="deslizar icono-menu fa fa-bars fa-2x ">
		    </i>
		    </span> 
			<h4 class="center-align"><span class="hide-on-small-only">Agregar</span> Personas</h4>		    
		</nav>
	</div>    

  <ul id="slide-out" class="side-nav ">
      <li>  
        <i class="iconos-pequeno prefix fa fa-user-o fa-2x"></i>        
      </li>
      <!-- <li>
          <div class="divider"></div>
        </li> -->  
    <li class=" ">
      <a href="/" class="btn"><i class="iconos-pequeno fa fa-home fa-1x" ></i> Inicio</a>
    </li>
    <li>
      <a href="/persona" class="active-btn btn"><i class="iconos-pequeno fa fa-user fa-1x" ></i> Agregar Personas </a> 
    </li>
    <li class=" ">
      <a href="/asignacion" class="btn "><i class="iconos-pequeno fa fa-desktop fa-1x" ></i> Equipos Asignados</a>
    </li>
    <li class=" ">
      <a href="/password" class="btn"><i class="iconos-pequeno fa fa-key fa-1x" ></i> Cambiar Contraseña</a>
    </li>
    <li class=" ">
      <a href="" class="btn"><i class="iconos-pequeno fa fa-cog fa-1x" ></i> Opciones</a>
    </li>
    <li class=" " >
      <a href="" class="btn"><i class="iconos-pequeno fa fa-power-off fa-1x" ></i> Cerrar Sección</a>
    </li>
  </ul>

<div>
		
	<div class="">
	<div class="row">
	<div class="col m12">
	<div class=" container1 col m5 s12">
		<div class=" row">
			<div class=" box-personas col m6 offset-m3 s12 x12">    
				<form action="" method="POST">{% csrf_token %}

				    <!--   Nombre y apellido   -->
				    <div class="input-field">    
				        <i class="prefix fa fa-user fa-3x"></i>
				        <input id="id_descripcion" name="nombre" type="text" required> 
				        <label for="id_descripcion" class="active">Nombre</label>
				    </div>

				    <!--  Descripción  -->
				    <div class="input-field">    
				        <i class="prefix fa fa-university fa-3x"></i>
				        <input id="id_modelo" name="departamento" type="text" required> 
				        <label for="id_modelo" class="active">Departamento</label>
				    </div>

				    <!--   Departamento   --> 
				    <div class=" center group navform wat-cf">
				        <button class="boton-agregar hoverable waves-effect" type="submit"> <i class="prefix fa fa-plus-square fa 3x separar"></i> Agregar</button>
				    </div>                        
				</form>
			</div>
		</div>
	</div>

	<!--   Tabla   --> 
	<div class="container1 col m7 s12 ">
		<div class=" row ancho nivel">

	                <table id="id_table" class="striped highlight centered">
	                    <thead>
		                    <tr>
		                        <th>Nombre</th>
		                        <th>Departamento</th>
		                    </tr>
	                    </thead>

	                    <tbody>
	                      {% for r in result %}
	                        <tr>
	                          <td>{{ r.nombre }}</td>
	                          <td>{{ r.departamento }}</td>
	                        </tr>
	                      {% endfor %}	                     
	                    </tbody>
	                </table>               
	                
		</div>
	</div>
	</div>
	</div>
	</div>

</div>
<script src="{% static '/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static '/materialize/js/materialize.min.js' %}"></script>
<script src="{% static '/materialize/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/materialize/js/jquery.dataTables.js' %}"></script>
<script src="{% static '/materialize/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static '/style.js' %}"></script>
    
</body>
</html>